spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/poke_auction
    username: poke_user
    password: poke_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080

kakao:
  client-id: ${KAKAO_REST_API_KEY}
  client-secret: ${KAKAO_CLIENT_SECRET}
  token-url: https://kauth.kakao.com/oauth/token
  user-info-url: https://kapi.kakao.com/v2/user/me

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600
  refresh-token-expiration: 604800
